import { ROUTE_CATEGORY } from "../constants/options.js";
import { authGuard } from "@auth0/auth0-vue";

export const librariesRoutes = [
  {
    path: "/vee-validate-hoc-field-simple",
    name: "VeeValidateHocFieldSimple",
    displayName: "Vee-Validate HOC Field Simple",
    category: ROUTE_CATEGORY.LIBRARIES,
    component: () => import("../views/library-examples/vee-validate/hoc-field-example.vue"),
  },
  {
    path: "/vee-validate-hoc-form-simple",
    name: "VeeValidateHocFormSimple",
    displayName: "Vee-Validate HOC Form Simple",
    category: ROUTE_CATEGORY.LIBRARIES,
    component: () => import("../views/library-examples/vee-validate/hoc-form-example.vue"),
  },
  {
    path: "/floating-ui-example",
    name: "FloatingUiExample",
    displayName: "Floating UI Example",
    category: ROUTE_CATEGORY.LIBRARIES,
    component: () => import("../views/library-examples/floating-ui/index.vue"),
  },
  {
    path: "/humanize-duration",
    name: "HumanizeDuration",
    displayName: "HumanizeDuration",
    category: ROUTE_CATEGORY.LIBRARIES,
    component: () => import("../views/library-examples/humanize-duration/index.vue"),
  },
  {
    path: "/debounced-requests",
    name: "DebouncedRequests",
    displayName: "DebouncedRequests",
    category: ROUTE_CATEGORY.LIBRARIES,
    component: () => import("../views/library-examples/debounced-requests/index.vue"),
  },
  {
    path: "/axios-get-params",
    name: "AxiosGetParams",
    displayName: "Axios Get Params",
    category: ROUTE_CATEGORY.LIBRARIES,
    component: () => import("../views/library-examples/axios-get-params/index.vue"),
  },
  {
    path: "/maska",
    name: "MaskaPage",
    displayName: "Maska Page",
    category: ROUTE_CATEGORY.LIBRARIES,
    component: () => import("../views/library-examples/MaskaPage.vue"),
  },
  {
    path: "/rxjs",
    name: "RxJS",
    displayName: "RxJS Example",
    category: ROUTE_CATEGORY.LIBRARIES,
    component: () => import("../views/library-examples/RxJS.vue"),
  },
  {
    path: "/pinia-example",
    name: "PiniaExample",
    displayName: "Pinia Example",
    category: ROUTE_CATEGORY.LIBRARIES,
    component: () => import("../views/library-examples/pinia-example/index.vue"),
  },
  {
    path: "/playwright-basics",
    name: "PlaywrightBasics",
    displayName: "Playwright Basics",
    category: ROUTE_CATEGORY.LIBRARIES,
    component: () => import("../views/library-examples/playwright-basics/index.vue"),
  },
  {
    path: "/date-fns",
    name: "DateFns",
    displayName: "DateFns Examples",
    category: ROUTE_CATEGORY.LIBRARIES,
    component: () => import("../views/library-examples/date-fns/index.vue"),
  },
  {
    path: "/auth0-universal-login",
    name: "Auth0UniversalLogin",
    displayName: "Auth0 Universal Login",
    category: ROUTE_CATEGORY.LIBRARIES,
    component: () => import("../views/library-examples/auth0-universal-login/index.vue"),
  },
  {
    path: "/auth0-dashboard",
    name: "Auth0Dashboard",
    displayName: "Auth0 Dashboard",
    category: ROUTE_CATEGORY.LIBRARIES,
    component: () => import("../views/library-examples/auth0-universal-login/dashboard.vue"),
    beforeEnter: authGuard,
  },
  {
    path: "/callback",
    name: "Auth0Callback",
    displayName: "Auth0 Callback",
    category: ROUTE_CATEGORY.LIBRARIES,
    component: () => import("../views/library-examples/auth0-universal-login/auth-0-callback.vue"),
  },
  {
    path: "/case-library-examples",
    name: "CaseLibraryExamples",
    displayName: "Case Library Examples",
    category: ROUTE_CATEGORY.LIBRARIES,
    component: () => import("../views/library-examples/case-library-examples/index.vue"),
  },
  {
    path: "/vue-echarts-example",
    name: "VueEChartsExample",
    displayName: "Vue ECharts Example",
    category: ROUTE_CATEGORY.LIBRARIES,
    component: () => import("../views/library-examples/vue-echarts-example/index.vue"),
  },
];
